var t= window.prompt("enter table value");
document.write("<br>");
document.write("<br>"+ t + "x 1" +"=" + t*1 );
document.write("<br>"+ t + "x 2" + "=" + t*2 );
document.write("<br>"+ t + "x 3" + "=" + t*3 );
document.write("<br>"+ t + "x 4" + "=" + t*4 );
document.write("<br>"+ t + "x 5" + "=" + t*5 );
document.write("<br>"+ t + "x 6" + "=" + t*6 );
document.write("<br>"+ t + "x 7" + "=" + t*7 );
document.write("<br>"+ t + "x 8" + "=" + t*8 );
document.write("<br>"+ t + "x 9" + "=" + t*9 );
document.write("<br>"+ t + "x 10" +"=" + t*10 );